setGameVarForMap({
  playerPos:{
  x: 0.50001,
  y: 2,
  z: 0.50001,
  deg: 0,
  vel: new vector(0, 0, 0)
  },
  playerWidth:0.9,
  speed:1,
  climbableBlocks:0,
  tiles:[],
  troxelLink:'https://cakenggt.github.io/Troxel/#m=CAcIAACYTAD/AJlMAP8AbjcA/wCWSwD/AHg8AP8AXC4A/wCiUQD/AIRCAP8AAH8A/wAAjQD/AAB1AP8AAGgA/wAAnAD/AACdAP8AAJsA/wAAiQD/gkCBAMPDw/+GQAC8vLz/AL+/v/+GQADCwsL/iEAAv7+//4ZACf//APAAkUgA/wBxOAD/AH4/AP8Ank8A/wBjMQD/AJBIAP8AZTIA/wCcTgD/AAB4AP8AAJQA/wAAZAD/AACYAP8AAHsA/wAAagD/AAB5AP8AAGQA/4VAAACXAP+NQADAwMD/AL6+vv+GQAC/v7//AL6+vv+HQACGQwD/AKFQAP8AfT4A/wCDQQD/AIJBAP8An08A/wCJRAD/AIZDAP8AAGAA/wAAdAD/QAAAmgD/AACiAP8AAHwA/wAAfwD/AACJAP+nQABnMwD/AJxOAP8AfT4A/wBqNQD/AIxGAP8AikUA/wCWSwD/AJdLAP8AAHMA/wAAWgD/AACFAP8AAF4A/wAAiwD/AACJAP8AAI4A/wAAXwD/p0AAdzsA/wCkUgD/AJ1OAP8AmUwA/wCNRgD/AFotAP8AajUA/wB0OgD/AACTAP8AAJUA/0AAAKQA/wAAjwD/QAAAbAD/AABuAP+nQACQSAD/AH0+AP8AZjMA/wCTSQD/AIFAAP8AiEQA/wCfTwD/AJBIAP+BAABpAP8AAGgA/wAAiAD/AACEAP8AAFsA/wAAZgD/AAB8AP+nQACSSQD/AH8/AP8AiEQA/wBzOQD/AINBAP8AkUgA/wBlMgD/AGs1AP8AAJkA/wAAkAD/AABoAP8AAJUA/wAAagD/AABgAP9AAACXAP+CQAAAZwD/o0AAnE4A/wBbLQD/AKJRAP8AdDoA/wCfTwD/AKJRAP8Ah0MA/wCWSwD/AACWAP8AAHQA/wAAYwD/AACCAP8AAIcA/wAAYAD/AACQAP8AAFwA/6dA'
});
