setGameVarForMap({
  playerPos:{
  x: 0.50001,
  y: 2,
  z: 0.50001,
  deg: 0,
  vel: new vector(0, 0, 0)
  },
  playerWidth:0.9,
  speed:1,
  climbableBlocks:0,
  tiles:[],
  troxelLink:'https://cakenggt.github.io/Troxel/#m=CAcIAFUAYgCYTAD/AJlMAP8AbjcA/wCWSwD/AHg8AP8AXC4A/wCiUQD/AIRCAP8AAH8A/wAAjQD/AAB1AP8AAGgA/wAAnAD/AACdAP8AAJsA/wAAiQD/AMPDw/8AvLy8/wC/v7//AMLCwv8R//8A8ACRSAD/AHE4AP8Afj8A/wCeTwD/AGMxAP8AkEgA/wBlMgD/AJxOAP8AAHgA/wAAlAD/AABkAP8AAJgA/wAAewD/AABqAP8AAHkA/wAAlwD/AMDAwP8Avr6+/wCGQwD/AKFQAP8AfT4A/wCDQQD/AIJBAP8An08A/wCJRAD/AABgAP8AAHQA/wAAmgD/AACiAP8AAHwA/wBnMwD/AGo1AP8AjEYA/wCKRQD/AJdLAP8AAHMA/wAAWgD/AACFAP8AAF4A/wAAiwD/AACOAP8AAF8A/wB3OwD/AKRSAP8AnU4A/wCNRgD/AFotAP8AdDoA/wAAkwD/AACVAP8AAKQA/wAAjwD/AABsAP8AAG4A/wBmMwD/AJNJAP8AgUAA/wCIRAD/AABpAP8AAIgA/wAAhAD/AABbAP8AAGYA/wCSSQD/AH8/AP8AczkA/wBrNQD/AACZAP8AAJAA/wAAZwD/AFstAP8Ah0MA/wAAlgD/AABjAP8AAIIA/wAAhwD/AABcAP8BAgMEBQYHCAkKCwwNDg8QgQCAEYUAEhOFABSHABOFABUWFxgZGhscHR4fICEiIyQghAAljAAmJ4UAEyeGACgpKissLS4oLzAAMTIzCRCmADQdKjU2NwQ4OTo7PD0QPj+mAEBBQgJDRDVFRkcASEkASkumABsqTE1OTy0bgFAMUVJTVDOmAFVWT1crFhxYWVoMRyMvACWBAFuiAB1cB0UtB10EXjBfYGEvWmKmAA=='
});
