setGameVarForMap({
  playerPos:{
  x: 0.50001,
  y: 2,
  z: 0.50001,
  deg: 0,
  vel: new vector(0, 0, 0)
  },
  playerWidth:0.9,
  playerJump:4,
  climbableBlocks:0,
  tiles:[],
  troxelLink:'https://cakenggt.github.io/Troxel/#m=CAcIAACYTAD/AJFIAP8AhkMA/wBnMwD/AHc7AP8AkEgA/wCSSQD/AJxOAP8AAH8A/wAAeAD/AABgAP8AAHMA/wAAkwD/AABpAP8AAJkA/wAAlgD/p0AAmUwA/wBxOAD/AKFQAP8AnE4A/wCkUgD/AH0+AP8Afz8A/wBbLQD/AACNAP8AAJQA/wAAdAD/AABaAP8AAJUA/wAAaQD/AACQAP8AAHQA/6dAAG43AP8Afj8A/4EAfT4A/wCdTgD/AGYzAP8AiEQA/wCiUQD/AAB1AP8AAGQA/0AAAIUA/0CBAABoAP8AAGMA/6dAAJZLAP8Ank8A/wCDQQD/AGo1AP8AmUwA/wCTSQD/AHM5AP8AdDoA/wAAaAD/AACYAP8AAJoA/wAAXgD/AACkAP8AAIgA/wAAlQD/AACCAP8Aw8PD/4RAAABnAP+gQAB4PAD/AGMxAP8AgkEA/wCMRgD/AI1GAP8AgUAA/wCDQQD/AJ9PAP8AAJwA/wAAewD/AACiAP8AAIsA/wAAjwD/AACEAP8AAGoA/wAAhwD/AMPDw/+GQAC8vLz/nkAAXC4A/wCQSAD/AJ9PAP8AikUA/wBaLQD/AIhEAP8AkUgA/wCiUQD/AACdAP8AAGoA/wAAfAD/AACJAP9AAABbAP+BAABgAP+HQAC/v7//hkAAwsLC/wDAwMD/lUAAolEA/wBlMgD/AIlEAP8AlksA/wBqNQD/AJ9PAP8AZTIA/wCHQwD/AACbAP8AAHkA/wAAfwD/AACOAP8AAGwA/wAAZgD/QAAAkAD/QAAAlwD/jkAAvr6+/4ZAAL+/v/+NQACEQgD/AJxOAP8AhkMA/wCXSwD/AHQ6AP8AkEgA/wBrNQD/AJZLAP8AAIkA/wAAZAD/AACJAP8AAF8A/wAAbgD/AAB8AP8AAJcA/wAAXAD/l0AAv7+//wC+vr7/hUAJ//8A8IZA'
});
